version: '3'

services:
  drawtogether:
    container_name: drawtogether
    image: pazka/drawtogether:latest
    ports:
      - "9001:80"
    volumes:
      - ./uploads:/app/front/build/uploads